### PR TITLE
Add a try clause to prevent display if openbox is not installed

### PR DESCRIPTION
**Pull request by agaida**

### CODE REVIEW

**Comment by pmattern** [comment]
Not sure whether we really need this. Both at build and runtime ObConf-Qt depends on ObRender. This library belongs to Openbox which is hence available anyway.

**Comment by agaida** [comment]
Nope - not in any case - that might be so in arch, but not in several other distributions that deliver build- and runtime things separated. One might think of builds in a build chroot.
```
obconf-qt
  Depends: libc6
  Depends: libglib2.0-0
  Depends: libobrender32v5
  Depends: libobt2v5
  Depends: libqt5core5a
  Depends: libqt5gui5
  Depends: libqt5widgets5
  Depends: libqt5x11extras5
  Depends: libstdc++6
  Depends: libx11-6
  Depends: libxml2
  Recommends: obconf-qt-l10n
```
So there is no direct dependency to openbox - maybe downstream should depend on openbox and done. Same as for compton - should a tool that write some configurations for a program (indipendent) depend on this program?

**Comment by agaida** [comment]
bah - reading my post again - a dependcy on openbox is the better solution - had a look into obconf. Same for compton-conf.

**Comment by pmattern** [comment]
For the record, the dependency on ObRender mandates Openbox at runtime on Debian as well:
```
# ldd `which obconf-qt` | grep -i obrender
  libobrender.so.32 => /usr/lib/x86_64-linux-gnu/libobrender.so.32 (0x00007fca0cf45000)
# dpkg --search /usr/lib/x86_64-linux-gnu/libobrender.so.32 
  libobrender32v5: /usr/lib/x86_64-linux-gnu/libobrender.so.32
# apt-cache rdepends libobrender32v5
  [...]
  openbox
```

**Comment by agaida** [comment]
reverse dependencies are not depenencies - reverse dependencies mean: which programs depend on $foo - as one could see in the apt output
```
% LANG=C aptitude show libobrender32v5
Package: libobrender32v5                 
Version: 3.6.1-3
State: installed
Automatically installed: no
Priority: optional
Section: libs
Maintainer: Mateusz ??ukasik <mati75@linuxmint.pl>
Architecture: amd64
Uncompressed Size: 163 k
Depends: libc6 (>= 2.14), libcairo2 (>= 1.2.4), libfontconfig1 (>= 2.11),
         libfreetype6 (>= 2.2.1), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0
         (>= 2.35.9), libice6 (>= 1:1.0.0), libimlib2 (>= 1.4.5), libobt2v5 (>=
         3.6.0), libpango-1.0-0 (>= 1.18.0), libpangoft2-1.0-0 (>= 1.14.0),
         libpangoxft-1.0-0 (>= 1.14.0), librsvg2-2 (>= 2.14.4), libsm6,
         libx11-6, libxft2 (> 2.1.1), libxml2 (>= 2.6.27)
Conflicts: libobrender15, libobrender16, libobrender32
Replaces: libobrender15, libobrender16, libobrender32
Description: rendering library for openbox themes
```

**Comment by pmattern** [comment]
But proper packaging will result in Openbox representing a dependency of the package providing binary `obconv-qt`. And that's what actually matters, isn't it?

**Pull request closed without merging**
