### PR TITLE
Small build fix (themes dir path)

### PR DESCRIPTION
**Pull request by jauhien**
Fix Gentoo bug 556000 (https://bugs.gentoo.org/show_bug.cgi?id=556000), thanks to Heiko Schäfer.

### CODE REVIEW

**Comment by jubalh** [comment]
Correct. GTM.

**Comment by luis-pereira** [comment]
Thanks @jauhien

**Comment by velnias75** [comment]
Sometimes my strange behaviour to watch the building process can even be good for something :smile:

**Comment by luis-pereira** [comment]
@jauhien @velnias75 Update: We now use [GNUInstallDirs](https://github.com/lxde/obconf-qt/commit/7ac0da260dd02de4d0eb8e99e6dbecd9815b8d7f)

**Pull request merged**
